package org.redhat.demo;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.3
 * 2018-01-17T17:45:54.398-05:00
 * Generated source version: 3.1.3
 * 
 */
@WebService(targetNamespace = "http://demo.redhat.org/", name = "ClaimServicePortType")
@XmlSeeAlso({ObjectFactory.class})
public interface ClaimServicePortType {

    @WebMethod
    @RequestWrapper(localName = "apply", targetNamespace = "http://demo.redhat.org/", className = "org.redhat.demo.Apply")
    @ResponseWrapper(localName = "applyResponse", targetNamespace = "http://demo.redhat.org/", className = "org.redhat.demo.ApplyResponse")
    @WebResult(name = "return", targetNamespace = "")
    public org.redhat.demo.ClaimOutput apply(
        @WebParam(name = "arg0", targetNamespace = "http://demo.redhat.org/")
        org.redhat.demo.ClaimInput arg0
    );
}
